# Generated by Django 3.2 on 2021-04-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='red',
            field=models.BooleanField(default=False),
        ),
    ]
