# Generated by Django 3.2 on 2021-04-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_blue'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='green',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='orange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='yellow',
            field=models.BooleanField(default=False),
        ),
    ]
